service: cvs-tsk-vt-booking-init
useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript
provider:
  region: eu-west-1
  name: aws
  runtime: nodejs14.x

functions:
  dynamoBooking:
    handler: src/handler/dynamo.handler
    events:
      - stream:
          type: dynamodb
